CREATE TABLE IF NOT EXISTS `USER` (
	`ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`USER_NAME` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '使用者名稱',
    `PASSWORD` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '密碼',
	`EMAIL` VARCHAR(80) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'email',
	`AVATAR_URL` VARCHAR(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '地址',
    `CREATED_DATE` DATETIME DEFAULT NULL COMMENT '建立時間',
    `UPDATED_DATE` DATETIME DEFAULT NULL COMMENT '更新時間',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='使用者';