version: "3.9"
services:
  web:
    container_name: Nextjs
    image: "${WEB_IMAGE}:${WEB_IMAGE_VERSION}"
    restart: always
    # environment:
    #   DOMAIN: Gin
  db:
    container_name: Mysql
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_MIGRATION_FILES_PATH}:docker-entrypoint-initdb.d"
  proxy:
    container_name: Nginx
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_HOST: ${DOMAIN}
    volumes:
      - "./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template"
    depends_on:
      - web
  
