version: "3.9"
services:
  web:
    container_name: Nextjs
    image: "${WEB_IMAGE}:${WEB_IMAGE_VERSION}"
    restart: always
    # environment:
    #   DOMAIN: Gin
  proxy:
    container_name: Nginx
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_HOST: ${DOMAIN}
    volumes:
      - "./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template"
    depends_on:
      - web
