# Install dependencies only when needed
FROM node:16-alpine AS deps
WORKDIR /app
COPY . .
RUN rm -rf package-lock.json
RUN npm i

# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app

ENV NODE_ENV production

COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN rm -rf .next
RUN npm run build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "start", "--", "-p", "80"]
