version: '3.9'

services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jira_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - 3306:3306
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"