version: '3.9'

services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "jira_db"
    ports:
      - 3306:3306
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"